sudo: required
services:
  - docker

before_install:
  - docker build -t beatsbyalif/pico-test -f ./front/DockerFile.dev ./front

script:
  - docker run -e CI=true beatsbyalif/pico-test npm run test -- --coverage

after_success:
  - docker build -t beatsbyalif/pico-front ./front
  - docker build -t beatsbyalif/pico-server ./server
  - docker build -t beatsbyalif/pico-nginx ./nginx
  # Login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images
  - docker push beatsbyalif/pico-front
  - docker push beatsbyalif/pico-server
  - docker push beatsbyalif/pico-nginx

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dock-multi"
  env: "Dock-multi-env "
  bucket_name: "elasticbeanstalk-us-east-2-246211615161"
  bucket_path: "dock-multi"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
