version: "3.8"

services:
  nginx:
    restart: always
    image: beatsbyalif/pico-nginx
    depends_on:
      - api
      - front
    ports:
      - 80:80
  front:
    image: beatsbyalif/pico-front
  api:
    image: beatsbyalif/pico-server
    restart: on-failure
    stdin_open: true
    tty: true
