version: "3.8"

services:
  nginx:
    restart: always
    image: beatsbyalif/pico-nginx
    ports:
      - 80:80
  app:
    image: beatsbyalif/pico-front
    ports:
      - 3000:3000
  api:
    image: beatsbyalif/pico-server
    restart: on-failure
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
