version: "3.8"

services:
  nginx:
    restart: always
    build: beatsbyalif/pico-nginx
    ports:
      - 80:80
  app:
    build: beatsbyalif/pico-front
    ports:
      - 3000:3000
  mysqldb:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQLDB_USER: $MYSQLDB_USER
      MYSQLDB_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  api:
    depends_on:
      - mysqldb
    build: beatsbyalif/pico-server
    restart: on-failure
    ports:
      - 8080:8080
    stdin_open: true
    tty: true

volumes:
  db:
