# server:
#    port: 8082
   
spring:
   datasource:
      url: jdbc:mysql://${MYSQL_HOST:mysqldb}:${MYSQL_PORT:3306}/${MYSQLDB_DATABASE:picogram}
      username: ${MYSQLDB_USER:root}
      password: ${MYSQLDB_ROOT_PASSWORD:password}
      driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: update
   # hikari:
   #    maxLifetime: 20000
 
        
    
 